GET  http://localhost:8080/personaje/
### 
POST http://localhost:8080/personaje/
Content-Type: application/json

{
    "id": 3,
    "name": "Macho Sanchez",
    "status": "Gayerrrr",
    "species":"Animalrrrrr",
    "img": "https://rickandmortyapi.com/api/character/avatar/363.jpeg"
}

### 